FROM ubuntu
USER root
RUN apt-get update && apt-get install openssh-server sudo -y && useradd -m user && usermod -aG sudo user && echo 'user:password' | chpasswd && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && apt-get clean
USER user
RUN mkdir /home/user/.ssh && touch /home/user/.ssh/authorized_keys 
COPY ./id_rsa.pub /home/user/.ssh/authorized_keys
USER root
CMD ["service","ssh","start","-D"]	