FROM archlinux:latest

RUN pacman -Syu && pacman -S --noconfirm openssh sudo -y && useradd -m user && usermod -aG sudo user && echo 'root:password' | chpasswd && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && pacman -Sc && mkdir /root/.ssh && touch /root/.ssh/authorized_keys  && chsh -s /bin/bash

CMD ["service","ssh","start","-D"]	
