# Use the official Ubuntu base image
FROM ubuntu:latest

# Set non-interactive mode for package installations
ENV DEBIAN_FRONTEND=noninteractive

# Update package repositories and install essential packages
# Combine all apt-get commands into one RUN instruction to reduce the number of layers
# Clean up in the same layer to reduce image size
RUN apt-get update && \
    apt-get install -y \
    nano \
    rsync \
    iproute2 \
    openssh-client \
    git \
    curl \
    openssh-server \
    sudo && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Set the password for the 'root' user
RUN echo 'root:password' | chpasswd

# Configure SSH settings to allow password authentication
RUN sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Create the .ssh directory and an empty authorized_keys file for the 'root' user
RUN mkdir -p /root/.ssh && \
    touch /root/.ssh/authorized_keys

# Change the shell for the 'root' user to /bin/bash
# No need to switch to root user as Docker runs commands as root by default
RUN chsh -s /bin/bash

# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]
