# Use the official Ubuntu base image
FROM ubuntu:latest

# Set non-interactive mode for package installations
ENV DEBIAN_FRONTEND=noninteractive

# Update package repositories and install essential packages
# Combine all apt-get commands into one RUN instruction to reduce the number of layers
# Clean up in the same layer to reduce image size
RUN apt-get update && \
    apt-get install -y \
    nano \
    rsync \
    iproute2 \
    openssh-client \
    git \
    curl \
    openssh-server \
    sudo && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    echo 'root:password' | chpasswd && \
    echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config && \
    mkdir -p /root/.ssh && \
    touch /root/.ssh/authorized_keys && \
    chsh -s /bin/bash


# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]
