FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
USER root
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y nano rsync iproute2 openssh-client openssh-server sudo git curl docker.io apache2 && useradd -m user && usermod -aG sudo user && echo 'user:password' | chpasswd && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && apt-get clean && chsh -s /bin/bash
USER user
RUN mkdir /home/user/.ssh && touch /home/user/.ssh/authorized_keys  
USER root
CMD [ "service","ssh","start","-D" ]