# Use the official varadbelwalkar/base_ubuntu
FROM varadbelwalkar/base_ubuntu


RUN apt-get update -y && apt-get install -y \
    default-jdk && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean 


# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]