# Use the official varadbelwalkar/python
FROM varadbelwalkar/python


RUN pip install numpy pandas scikit-learn matplotlib jupyter && jupyter notebook --generate-config
WORKDIR /app
# Create and set the start.sh script as a multi-line command
RUN echo '#!/bin/bash' > /app/start.sh && \
    echo 'CONTAINER_IP=$(hostname -I)' >> /app/start.sh && \
    echo 'jupyter notebook --ip=$CONTAINER_IP --port=8000 --no-browser --allow-root &' >> /app/start.sh && \
    echo 'service ssh start -D' >> /app/start.sh && \
    chmod +x /app/start.sh

# Start the script by overwriting the CMD
CMD ["/app/start.sh"]