# Use the official Ubuntu base image
FROM ubuntu:latest

# Set non-interactive mode for package installations
ENV DEBIAN_FRONTEND=noninteractive

# Update package repositories and install essential packages
# Combine all apt-get commands into one RUN instruction to reduce the number of layers
# Clean up in the same layer to reduce image size
RUN apt-get update && \
    apt-get install -y \
    nano \
    rsync \
    iproute2 \
    openssh-client \
    git \
    curl \
    openssh-server \
    sudo && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Add the 'user' to the sudo group and set their password
RUN useradd -m user && \
    usermod -aG sudo user && \
    echo 'user:password' | chpasswd

# Configure SSH settings
RUN echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config

# Change the shell for the 'user' to /bin/bash
RUN chsh -s /bin/bash user

# Create an empty authorized_keys file in the user's home directory
RUN mkdir -p /home/user/.ssh && \
    touch /home/user/.ssh/authorized_keys

# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]
