# Use a base image (e.g., Ubuntu) and set the desired version
FROM ubuntu:latest

# Set environment variables for non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install required packages
# Combine all apt-get commands into one RUN instruction to reduce the number of layers
# Clean up in the same layer to reduce image size
RUN apt-get update && apt-get install -y \
    nano \
    rsync \
    iproute2 \
    openssh-client \
    openssh-server \
    sudo \
    git \
    curl \
    docker.io \
    kubeadm \
    kubelet \
    kubectl \
    kubernetes-cni && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Configure SSH server for key authentication only and disable password authentication
RUN sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Start SSH server and Kubernetes components on container start
CMD service ssh start -D && kubeadm init --apiserver-advertise-address=0.0.0.0 --pod-network-cidr=10.244.0.0/16
