# Use the official varadbelwalkar/base_ubuntu
FROM varadbelwalkar/base_ubuntu


RUN curl -OL https://golang.org/dl/go1.16.7.linux-amd64.tar.gz && \
    tar -C /usr/local -xvf go1.16.7.linux-amd64.tar.gz && \
    rm go1.16.7.linux-amd64.tar.gz

# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]
