# Use the official varadbelwalkar/base_ubuntu
FROM varadbelwalkar/nested-docker

RUN RUN apt-get update -y && apt-get install -y \
    docker.io && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
    install minikube-linux-amd64 /usr/local/bin/minikube


# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]