# Use the official Ubuntu base image
FROM ubuntu

# Set non-interactive mode for package installations
ENV DEBIAN_FRONTEND noninteractive

# Update package repositories and install essential packages
RUN apt-get update \
    && apt-get install -y \
    nano \
    rsync \
    iproute2 \
    openssh-client \
    git \
    curl \
    openssh-server \
    sudo \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Create a non-root user
RUN useradd -m user \
    && usermod -aG sudo user \
    && echo 'user:password' | chpasswd

# Configure SSH server
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && mkdir /var/run/sshd

# Switch to the 'user' for configuring SSH keys
USER user

# Create an empty authorized_keys file in the user's home directory
RUN mkdir /home/user/.ssh \
    && touch /home/user/.ssh/authorized_keys

# Switch back to the root user for the final command
USER root

# Start the SSH service in the foreground
CMD ["/usr/sbin/sshd", "-D"]
