# Use the official varadbelwalkar/base_ubuntu
FROM varadbelwalkar/base_ubuntu


RUN apt-get install -y \
    python3 \
    virtualenv && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean


# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]
