# Use the official Ubuntu base image
FROM ubuntu:latest

# Set non-interactive mode for package installations
ENV DEBIAN_FRONTEND=noninteractive

# Update package repositories, upgrade, and install essential packages
# Combine all apt-get commands into one RUN instruction to reduce the number of layers
# Clean up in the same layer to reduce image size
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    nano \
    rsync \
    iproute2 \
    openssh-client \
    openssh-server \
    sudo \
    git \
    curl \
    python3 \
    virtualenv \
    apache2 && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

# Configure SSH settings
RUN echo "PasswordAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config

# Change the shell for the root user to /bin/bash
# No need to switch to root user as Docker runs commands as root by default
RUN chsh -s /bin/bash

# Create the .ssh directory and an empty authorized_keys file for the root user
RUN mkdir -p /root/.ssh && \
    touch /root/.ssh/authorized_keys

# Start the SSH service in the foreground
CMD ["service", "ssh", "start", "-D"]
